# Generated by Django 3.0.6 on 2020-06-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
